#!/usr/bin/env python3
"""Enable test admin login for development/testing"""

import os
import sys

def enable_test_admin():
    """Set environment variables to enable test admin login"""
    
    # Set the environment variables
    os.environ["ENABLE_TEST_ADMIN"] = "true"
    os.environ["TEST_ADMIN_PASSWORD"] = "testadmin123"
    os.environ["ALLOW_MOCK_LOGIN"] = "true"
    
    print("✅ Test admin login enabled!")
    print("\n📝 Test Admin Details:")
    print("   URL: http://localhost:5000/auth/test-admin")
    print("   Password: testadmin123")
    print("\n⚠️  WARNING: This is for testing only. Never use in production!")
    
    # Create or update .env file
    env_file = ".env"
    env_vars = {
        "ENABLE_TEST_ADMIN": "true",
        "TEST_ADMIN_PASSWORD": "testadmin123",
        "ALLOW_MOCK_LOGIN": "true"
    }
    
    # Read existing .env if it exists
    existing_vars = {}
    if os.path.exists(env_file):
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_vars[key.strip()] = value.strip()
    
    # Update with new test admin vars
    existing_vars.update(env_vars)
    
    # Write back to .env
    with open(env_file, 'w') as f:
        f.write("# Environment Configuration\n")
        f.write("# Auto-generated by enable_test_admin.py\n\n")
        
        # Write test admin vars first
        f.write("# Test Admin Configuration (REMOVE IN PRODUCTION)\n")
        for key in ["ENABLE_TEST_ADMIN", "TEST_ADMIN_PASSWORD", "ALLOW_MOCK_LOGIN"]:
            if key in existing_vars:
                f.write(f"{key}={existing_vars[key]}\n")
                del existing_vars[key]
        
        # Write other existing vars
        if existing_vars:
            f.write("\n# Other Configuration\n")
            for key, value in existing_vars.items():
                f.write(f"{key}={value}\n")
    
    print(f"\n✅ Updated {env_file} with test admin configuration")
    print("\n🚀 To use test admin login:")
    print("   1. Restart the Flask application")
    print("   2. Navigate to: /auth/test-admin")
    print("   3. Enter password: testadmin123")

if __name__ == "__main__":
    enable_test_admin()