[tool.black]
line-length = 88
target-version = ["py311", "py310", "py39"]

[tool.ruff]
line-length = 100
target-version = "py311"
exclude = [".venv", "venv", "logs", "downloads", "instance"]

[tool.ruff.isort]
known-first-party = ["app", "blueprints", "models", "utils"]
force-single-line = false
combine-as-imports = true

[tool.ruff.lint]
ignore = ["E501"]
